# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/weigao/PHY-Project/example/AU200/fpga_10g/fpga/fpga.runs/synth_1/fpga.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcu200-fsgd2104-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/weigao/PHY-Project/example/AU200/fpga_10g/fpga/fpga.cache/wt [current_project]
set_property parent.project_path /home/weigao/PHY-Project/example/AU200/fpga_10g/fpga/fpga.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/weigao/PHY-Project/example/AU200/fpga_10g/fpga/fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/lib/axis/rtl/arbiter.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/arp.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/arp_cache.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/arp_eth_rx.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/arp_eth_tx.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/lib/axis/rtl/axis_async_fifo.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/lib/axis/rtl/axis_async_fifo_adapter.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/lib/axis/rtl/axis_fifo.v
  /home/weigao/PHY-Project/IPG_RTL/axis_xgmii_rx_64.v
  /home/weigao/PHY-Project/IPG_RTL/axis_xgmii_tx_64.v
  /home/weigao/PHY-Project/Buffer_RTL/buf_mon.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/rtl/debounce_switch.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/eth_arb_mux.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/eth_axis_rx.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/eth_axis_tx.v
  /home/weigao/PHY-Project/IPG_RTL/eth_mac_10g.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/eth_mac_10g_fifo.v
  /home/weigao/PHY-Project/IPG_RTL/eth_phy_10g.v
  /home/weigao/PHY-Project/IPG_RTL/eth_phy_10g_rx.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/eth_phy_10g_rx_ber_mon.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/eth_phy_10g_rx_frame_sync.v
  /home/weigao/PHY-Project/IPG_RTL/eth_phy_10g_rx_if.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/eth_phy_10g_rx_watchdog.v
  /home/weigao/PHY-Project/IPG_RTL/eth_phy_10g_tx.v
  /home/weigao/PHY-Project/IPG_RTL/eth_phy_10g_tx_if.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/rtl/eth_xcvr_phy_wrapper.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/rtl/fpga_core.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/ip_64.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/ip_arb_mux.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/ip_complete_64.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/ip_eth_rx_64.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/ip_eth_tx_64.v
  /home/weigao/PHY-Project/IPG_RTL/ipg_rreq_proc.v
  /home/weigao/PHY-Project/IPG_RTL/ipg_rresp_proc.v
  /home/weigao/PHY-Project/IPG_RTL/ipg_rx.v
  /home/weigao/PHY-Project/IPG_RTL/ipg_tx.v
  /home/weigao/PHY-Project/IPG_RTL/ipg_wreq_proc.v
  /home/weigao/PHY-Project/Buffer_RTL/job_fifo_buf.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/lfsr.v
  /home/weigao/PHY-Project/Buffer_RTL/mem_fifo_buf.v
  /home/weigao/PHY-Project/Buffer_RTL/net_fifo_buf.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/lib/axis/rtl/priority_encoder.v
  /home/weigao/PHY-Project/Buffer_RTL/req_fifo_buf.v
  /home/weigao/PHY-Project/IPG_RTL/resp_adapter.v
  /home/weigao/PHY-Project/Buffer_RTL/resp_fifo_buf.v
  /home/weigao/PHY-Project/IPG_RTL/shim_control.v
  /home/weigao/PHY-Project/Buffer_RTL/shim_fifo_buf.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/lib/axis/rtl/sync_reset.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/rtl/sync_signal.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/udp_64.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/udp_checksum_gen_64.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/udp_complete_64.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/udp_ip_rx_64.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/rtl/udp_ip_tx_64.v
  /home/weigao/PHY-Project/IPG_RTL/xgmii_baser_dec_64.v
  /home/weigao/PHY-Project/IPG_RTL/xgmii_baser_enc_64.v
  /home/weigao/PHY-Project/example/AU200/fpga_10g/rtl/fpga.v
}
read_ip -quiet /home/weigao/PHY-Project/example/AU200/fpga_10g/fpga/fpga.srcs/sources_1/ip/eth_xcvr_gt_full/eth_xcvr_gt_full.xci
set_property used_in_implementation false [get_files -all /home/weigao/PHY-Project/example/AU200/fpga_10g/fpga/fpga.gen/sources_1/ip/eth_xcvr_gt_full/synth/eth_xcvr_gt_full_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/weigao/PHY-Project/example/AU200/fpga_10g/fpga/fpga.gen/sources_1/ip/eth_xcvr_gt_full/synth/eth_xcvr_gt_full.xdc]

read_ip -quiet /home/weigao/PHY-Project/example/AU200/fpga_10g/fpga/fpga.srcs/sources_1/ip/eth_xcvr_gt_channel/eth_xcvr_gt_channel.xci
set_property used_in_implementation false [get_files -all /home/weigao/PHY-Project/example/AU200/fpga_10g/fpga/fpga.gen/sources_1/ip/eth_xcvr_gt_channel/synth/eth_xcvr_gt_channel_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/weigao/PHY-Project/example/AU200/fpga_10g/fpga/fpga.gen/sources_1/ip/eth_xcvr_gt_channel/synth/eth_xcvr_gt_channel.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/weigao/PHY-Project/example/AU200/fpga_10g/fpga.xdc
set_property used_in_implementation false [get_files /home/weigao/PHY-Project/example/AU200/fpga_10g/fpga.xdc]

read_xdc -unmanaged /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/syn/vivado/eth_mac_fifo.tcl
set_property used_in_implementation false [get_files /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/syn/vivado/eth_mac_fifo.tcl]

read_xdc -unmanaged /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/lib/axis/syn/vivado/axis_async_fifo.tcl
set_property used_in_implementation false [get_files /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/lib/axis/syn/vivado/axis_async_fifo.tcl]

read_xdc -unmanaged /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/lib/axis/syn/vivado/sync_reset.tcl
set_property used_in_implementation false [get_files /home/weigao/PHY-Project/example/AU200/fpga_10g/lib/eth/lib/axis/syn/vivado/sync_reset.tcl]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top fpga -part xcu200-fsgd2104-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga_utilization_synth.rpt -pb fpga_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
